# Generated by Django 3.2.6 on 2022-08-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tarjeta',
            options={},
        ),
    ]
