# Generated by Django 4.0.6 on 2022-08-17 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itbankFs', '0002_cliente_cuenta_prestamo_sucursal_tarjeta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
