# Generated by Django 4.0.6 on 2022-08-17 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itbankFs', '0003_rename_branch_id_cliente_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion',
            new_name='directions',
        ),
    ]
