# Generated by Django 4.0.6 on 2022-08-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itbankFs', '0004_rename_direccion_cliente_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='client_type',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
