# Generated by Django 3.2.6 on 2022-08-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itbankFs', '0005_tarjeta_client_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_type', models.TextField()),
                ('card_brand', models.TextField()),
                ('card_type', models.TextField()),
                ('card_number', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('card_issue_date', models.TextField()),
                ('card_expiration_date', models.TextField()),
            ],
        ),
    ]
