# Generated by Django 3.2.6 on 2022-08-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itbankFs', '0006_tipocliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='direccion',
            new_name='directions',
        ),
    ]
